module_country = "Country"
country = "Country"

country_ethnics = "Origin Country"
country_living = "Living In Country"

c_AF = "Afghanistan"
c_AX = "Åland Islands"
c_AL = "Albania"
c_DZ = "Algeria"
c_AS = "American Samoa"
c_AD = "Andorra"
c_AO = "Angola"
c_AI = "Anguilla"
c_AQ = "Antarctica"
c_AG = "Antigua and Barbuda"
c_AR = "Argentina"
c_AM = "Armenia"
c_AW = "Aruba"
c_AU = "Australia"
c_AT = "Austria"
c_AZ = "Azerbaijan"
c_BS = "Bahamas"
c_BH = "Bahrain"
c_BD = "Bangladesh"
c_BB = "Barbados"
c_BY = "Belarus"
c_BE = "Belgium"
c_BZ = "Belize"
c_BJ = "Benin"
c_BM = "Bermuda"
c_BT = "Bhutan"
c_BO = "Bolivia (Plurinational State of)"
c_BQ = "Bonaire, Sint Eustatius and Saba"
c_BA = "Bosnia and Herzegovina"
c_BW = "Botswana"
c_BV = "Bouvet Island"
c_BR = "Brazil"
c_IO = "British Indian Ocean Territory"
c_BN = "Brunei Darussalam"
c_BG = "Bulgaria"
c_BF = "Burkina Faso"
c_BI = "Burundi"
c_CV = "Cabo Verde"
c_KH = "Cambodia"
c_CM = "Cameroon"
c_CA = "Canada"
c_KY = "Cayman Islands"
c_CF = "Central African Republic"
c_TD = "Chad"
c_CL = "Chile"
c_CN = "China"
c_CX = "Christmas Island"
c_CC = "Cocos (Keeling) Islands"
c_CO = "Colombia"
c_KM = "Comoros"
c_CG = "Congo"
c_CD = "Congo, Democratic Republic of the"
c_CK = "Cook Islands"
c_CR = "Costa Rica"
c_CI = "Côte d'Ivoire"
c_HR = "Croatia"
c_CU = "Cuba"
c_CW = "Curaçao"
c_CY = "Cyprus"
c_CZ = "Czechia"
c_DK = "Denmark"
c_DJ = "Djibouti"
c_DM = "Dominica"
c_DO = "Dominican Republic"
c_EC = "Ecuador"
c_EG = "Egypt"
c_SV = "El Salvador"
c_GQ = "Equatorial Guinea"
c_ER = "Eritrea"
c_EE = "Estonia"
c_SZ = "Eswatini"
c_ET = "Ethiopia"
c_FK = "Falkland Islands (Malvinas)"
c_FO = "Faroe Islands"
c_FJ = "Fiji"
c_FI = "Finland"
c_FR = "France"
c_GF = "French Guiana"
c_PF = "French Polynesia"
c_TF = "French Southern Territories"
c_GA = "Gabon"
c_GM = "Gambia"
c_GE = "Georgia"
c_DE = "Germany"
c_GH = "Ghana"
c_GI = "Gibraltar"
c_GR = "Greece"
c_GL = "Greenland"
c_GD = "Grenada"
c_GP = "Guadeloupe"
c_GU = "Guam"
c_GT = "Guatemala"
c_GG = "Guernsey"
c_GN = "Guinea"
c_GW = "Guinea-Bissau"
c_GY = "Guyana"
c_HT = "Haiti"
c_HM = "Heard Island and McDonald Islands"
c_VA = "Holy See"
c_HN = "Honduras"
c_HK = "Hong Kong"
c_HU = "Hungary"
c_IS = "Iceland"
c_IN = "India"
c_ID = "Indonesia"
c_IR = "Iran (Islamic Republic of)"
c_IQ = "Iraq"
c_IE = "Ireland"
c_IM = "Isle of Man"
c_IL = "Israel"
c_IT = "Italy"
c_JM = "Jamaica"
c_JP = "Japan"
c_JE = "Jersey"
c_JO = "Jordan"
c_KZ = "Kazakhstan"
c_KE = "Kenya"
c_KI = "Kiribati"
c_KP = "Korea (Democratic People's Republic of)"
c_KR = "Korea, Republic of"
c_KW = "Kuwait"
c_KG = "Kyrgyzstan"
c_LA = "Lao People's Democratic Republic"
c_LV = "Latvia"
c_LB = "Lebanon"
c_LS = "Lesotho"
c_LR = "Liberia"
c_LY = "Libya"
c_LI = "Liechtenstein"
c_LT = "Lithuania"
c_LU = "Luxembourg"
c_MO = "Macao"
c_MG = "Madagascar"
c_MW = "Malawi"
c_MY = "Malaysia"
c_MV = "Maldives"
c_ML = "Mali"
c_MT = "Malta"
c_MH = "Marshall Islands"
c_MQ = "Martinique"
c_MR = "Mauritania"
c_MU = "Mauritius"
c_YT = "Mayotte"
c_MX = "Mexico"
c_FM = "Micronesia (Federated States of)"
c_MD = "Moldova, Republic of"
c_MC = "Monaco"
c_MN = "Mongolia"
c_ME = "Montenegro"
c_MS = "Montserrat"
c_MA = "Morocco"
c_MZ = "Mozambique"
c_MM = "Myanmar"
c_NA = "Namibia"
c_NR = "Nauru"
c_NP = "Nepal"
c_NL = "Netherlands"
c_NC = "New Caledonia"
c_NZ = "New Zealand"
c_NI = "Nicaragua"
c_NE = "Niger"
c_NG = "Nigeria"
c_NU = "Niue"
c_NF = "Norfolk Island"
c_MK = "North Macedonia"
c_MP = "Northern Mariana Islands"
c_NO = "Norway"
c_OM = "Oman"
c_PK = "Pakistan"
c_PW = "Palau"
c_PS = "Palestine, State of"
c_PA = "Panama"
c_PG = "Papua New Guinea"
c_PY = "Paraguay"
c_PE = "Peru"
c_PH = "Philippines"
c_PN = "Pitcairn"
c_PL = "Poland"
c_PT = "Portugal"
c_PR = "Puerto Rico"
c_QA = "Qatar"
c_RE = "Réunion"
c_RO = "Romania"
c_RU = "Russian Federation"
c_RW = "Rwanda"
c_BL = "Saint Barthélemy"
c_SH = "Saint Helena, Ascension and Tristan da Cunha"
c_KN = "Saint Kitts and Nevis"
c_LC = "Saint Lucia"
c_MF = "Saint Martin (French part)"
c_PM = "Saint Pierre and Miquelon"
c_VC = "Saint Vincent and the Grenadines"
c_WS = "Samoa"
c_SM = "San Marino"
c_ST = "Sao Tome and Principe"
c_SA = "Saudi Arabia"
c_SN = "Senegal"
c_RS = "Serbia"
c_SC = "Seychelles"
c_SL = "Sierra Leone"
c_SG = "Singapore"
c_SX = "Sint Maarten (Dutch part)"
c_SK = "Slovakia"
c_SI = "Slovenia"
c_SB = "Solomon Islands"
c_SO = "Somalia"
c_ZA = "South Africa"
c_GS = "South Georgia and the South Sandwich Islands"
c_SS = "South Sudan"
c_ES = "Spain"
c_LK = "Sri Lanka"
c_SD = "Sudan"
c_SR = "Suriname"
c_SJ = "Svalbard and Jan Mayen"
c_SE = "Sweden"
c_CH = "Switzerland"
c_SY = "Syrian Arab Republic"
c_TW = "Taiwan, Province of China"
c_TJ = "Tajikistan"
c_TZ = "Tanzania, United Republic of"
c_TH = "Thailand"
c_TL = "Timor-Leste"
c_TG = "Togo"
c_TK = "Tokelau"
c_TO = "Tonga"
c_TT = "Trinidad and Tobago"
c_TN = "Tunisia"
c_TR = "Turkey"
c_TM = "Turkmenistan"
c_TC = "Turks and Caicos Islands"
c_TV = "Tuvalu"
c_UG = "Uganda"
c_UA = "Ukraine"
c_AE = "United Arab Emirates"
c_GB = "United Kingdom of Great Britain and Northern Ireland"
c_US = "United States of America"
c_UM = "United States Minor Outlying Islands"
c_UY = "Uruguay"
c_UZ = "Uzbekistan"
c_VU = "Vanuatu"
c_VE = "Venezuela (Bolivarian Republic of)"
c_VN = "Viet Nam"
c_VG = "Virgin Islands (British)"
c_VI = "Virgin Islands (U.S.)"
c_WF = "Wallis and Futuna"
c_EH = "Western Sahara"
c_YE = "Yemen"
c_ZM = "Zambia"
c_ZW = "Zimbabwe"
